
# 構文
# モデル名.create(カラム名: '入れる値', カラム名: '入れる値')

#questionsマスタテーブル初期データ
Question.create(fatigue_category:'身体の疲労',question_content: '体がだるい・重いと感じますか？')
Question.create(fatigue_category:'身体の疲労',question_content: '食欲はありますか？')
Question.create(fatigue_category:'身体の疲労',question_content: '最近ぐっすり眠れていますか？')
Question.create(fatigue_category:'心の疲労',question_content: '感情の起伏が激しいと感じますか？')
Question.create(fatigue_category:'心の疲労',question_content: '孤独や寂しさを感じることが多いですか？')
Question.create(fatigue_category:'心の疲労',question_content: '気分が晴れない・イライラすることが多いですか？')
Question.create(fatigue_category:'脳の疲労',question_content: '集中力が続かないと感じますか？')
Question.create(fatigue_category:'脳の疲労',question_content: 'やるべきことに手がつけられませんか？')
Question.create(fatigue_category:'脳の疲労',question_content: '頭が働かない・ぼーっとする感じがありますか？')

#choicesマスタテーブル初期データ
Choice.create(question_id: 1,choice_content: 'まったく感じない',score: 0)
Choice.create(question_id: 1,choice_content: 'あまり感じない',score: 1)
Choice.create(question_id: 1,choice_content: 'どちらとも言えない',score: 2)
Choice.create(question_id: 1,choice_content: 'やや感じる',score: 3)
Choice.create(question_id: 1,choice_content: 'とても感じる',score: 4)
Choice.create(question_id: 2,choice_content: '食欲は適切で、ちょうどよく食べられている',score: 0)
Choice.create(question_id: 2,choice_content: 'やや食べすぎていると感じる',score: 1)
Choice.create(question_id: 2,choice_content: 'あまり食欲がなく、食事量が少ない',score: 2)
Choice.create(question_id: 2,choice_content: '明らかに食べすぎていると感じる',score: 3)
Choice.create(question_id: 2,choice_content: 'ほとんど食べられず、食欲がまったくない',score: 4)
Choice.create(question_id: 3,choice_content: 'とてもよく眠れており、すっきり目覚めた',score: 0)
Choice.create(question_id: 3,choice_content: '大体眠れており、日中も問題なく過ごせる',score: 1)
Choice.create(question_id: 3,choice_content: '時々眠れない日があり、やや眠気が残る',score: 2)
Choice.create(question_id: 3,choice_content: 'よく眠れず、寝不足を感じている',score: 3)
Choice.create(question_id: 3,choice_content: '寝すぎてしまい、起きてもだるさが残る・まったく眠れない',score: 4)
Choice.create(question_id: 4,choice_content: '感情は安定していて穏やかに過ごせている',score: 0)
Choice.create(question_id: 4,choice_content: '多少の波はあるが気にならない程度',score: 1)
Choice.create(question_id: 4,choice_content: '時々イライラや落ち込みを感じることがある',score: 2)
Choice.create(question_id: 4,choice_content: '感情の波があり、自分でもコントロールしにくい',score: 3)
Choice.create(question_id: 4,choice_content: '感情が大きく乱れ、日常生活にも影響が出ている',score: 4)
Choice.create(question_id: 5,choice_content: '安心できる人間関係があり孤独は感じていない',score: 0)
Choice.create(question_id: 5,choice_content: '少し寂しさを感じる時もあるが気にならない',score: 1)
Choice.create(question_id: 5,choice_content: '時々孤独や寂しさを感じることがある',score: 2)
Choice.create(question_id: 5,choice_content: '寂しさを感じる時間が多く、気分が落ち込みやすい',score: 3)
Choice.create(question_id: 5,choice_content: 'ほとんど常に孤独を感じていてつらい',score: 4)
Choice.create(question_id: 6,choice_content: '気分は良好で穏やかに過ごせている',score: 0)
Choice.create(question_id: 6,choice_content: '軽いストレスはあるが気にならない',score: 1)
Choice.create(question_id: 6,choice_content: 'たまに気分が落ち込んだりイライラすることがある',score: 2)
Choice.create(question_id: 6,choice_content: '気分の重さやイライラを感じる日が多い',score: 3)
Choice.create(question_id: 6,choice_content: 'ほとんど毎日ネガティブな感情に支配されている',score: 4)
Choice.create(question_id: 7,choice_content: '集中力は十分あり、作業に没頭できる',score: 0)
Choice.create(question_id: 7,choice_content: '少し注意がそれる時もあるが問題ない',score: 1)
Choice.create(question_id: 7,choice_content: 'ときどき集中が途切れて効率が下がる',score: 2)
Choice.create(question_id: 7,choice_content: '集中できない時間が多く、作業が進まないことがある',score: 3)
Choice.create(question_id: 7,choice_content: 'ほとんど集中できず、頭が働かない感じが続いている',score: 4)
Choice.create(question_id: 8,choice_content: 'やるべきことはスムーズにこなせている',score: 0)
Choice.create(question_id: 8,choice_content: '少し後回しにすることもあるが支障はない',score: 1)
Choice.create(question_id: 8,choice_content: '取りかかるのに少し時間がかかることがある',score: 2)
Choice.create(question_id: 8,choice_content: 'やるべきことが多く、手がつけられないことがある',score: 3)
Choice.create(question_id: 8,choice_content: '何も手につかず、先延ばしが続いてしまっている',score: 4)
Choice.create(question_id: 9,choice_content: '頭はすっきりしており、よく働いていると感じる',score: 0)
Choice.create(question_id: 9,choice_content: '多少のぼーっと感はあるが支障はない',score: 1)
Choice.create(question_id: 9,choice_content: 'ときどきぼーっとして思考が鈍くなることがある',score: 2)
Choice.create(question_id: 9,choice_content: '頭が回らず、考えるのがしんどく感じる時が多い',score: 3)
Choice.create(question_id: 9,choice_content: '常に思考が鈍く、判断力が落ちていると感じる',score: 4)

#diagnosis_resultsマスタテーブル初期データ
DiagnosisResult.create(pattern_code: '身体の疲労',result_summary: '身体の疲れが特に目立つ状態です。無理せず、身体を労わるケアを優先しましょう。',suggestion: 'ホットアイマスクや首元の温熱シートで筋肉をゆるめてリラックスしましょう。3〜5分の深呼吸を取り入れることで副交感神経を優位にできます。')
DiagnosisResult.create(pattern_code: '心の疲労',result_summary: '感情面での揺らぎが強いようです。心を落ち着かせる時間を持ちましょう。',suggestion: '心地よい香りのアロマやハーブティーを取り入れ、感情を整えましょう。好きな音楽を3分間だけ聴くのも効果的です。')
DiagnosisResult.create(pattern_code: '脳の疲労',result_summary: '考えすぎや集中疲れが見られます。脳を休ませる時間を意識してみましょう。',suggestion: '目を閉じて1〜3分間マインドフルネス呼吸を行いましょう。スマホやPCから目を離し、ぼーっと外の景色を眺めるのもおすすめです。')
DiagnosisResult.create(pattern_code: '身体と心の疲労',result_summary: '身体と心の両方に疲れが見えます。緊張をほぐしつつ心を落ち着けましょう。',suggestion: 'ぬるめのお湯に5分だけ手を浸す「手湯」がおすすめ。アロマを数滴加えると心も安らぎます。')
DiagnosisResult.create(pattern_code: '身体と脳の疲労',result_summary: '心と頭の両方が疲れているかもしれません。静かな場所で一人の時間を取るのもおすすめです。',suggestion: 'ネガティブな感情を紙に1分間だけ書き出し、破り捨てることで思考と感情のリセットができます。その後、温かい飲み物で一息を。')
DiagnosisResult.create(pattern_code: '心と脳の疲労',result_summary: '身体と脳がオーバーワーク気味です。軽い運動やしっかりした睡眠を心がけましょう。',suggestion: '5分間の目を閉じた「プチ瞑想」で脳を休め、ストレッチで身体をほぐしましょう。電子機器から少し離れるのも有効です。')
DiagnosisResult.create(pattern_code: '疲労なし',result_summary: '今日は全体的に安定しています。好きな方法で心身を整えると、より良い一日になりますよ。',suggestion: '気分の良さをより高めるために、自然音を聴きながらゆったりとした時間を過ごしましょう。軽い散歩もおすすめです。')
DiagnosisResult.create(pattern_code: '身体と心と脳の疲労',result_summary: '身体・心・思考すべてにお疲れのサインが見えます。できるだけゆっくり過ごす時間を意識してください。',suggestion: '静かな場所で5分間、自分の呼吸に意識を向けてみましょう。軽いストレッチと深呼吸の組み合わせもおすすめです。')
